---
# tasks file for server-setup
- name: install Rocketchat on ubuntu server
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    - ../secrets/sudo.yml

  tasks:
  - name: gathering OS vars
    debug:
      msg: "{{ ansible_facts }}"
  - include_tasks: Debian-apt.yml
    when: ansible_os_family == "Debian"

#installing Mongodb 5 on ubuntu
  - include_tasks: Ubuntu-mongodb.yml
    when: ansible_distribution == "Ubuntu"
    ignore_errors: true

#installing Node on ubuntu
  - include_tasks: Ubuntu-node.yml
    when: ansible_distribution == "Ubuntu"

#installing Rocketchat requirements on ubuntu
  - include_tasks: Ubuntu-rocketchat.yml
    when: ansible_distribution == "Ubuntu"

#install nginx and copy its configuration
  - include_tasks: Ubuntu-nginx.yml
    when: ansible_distribution == "Ubuntu"
