---
# handlers file for server-setup
- name: apt_update
  service:
    update_cache: yes

- name: mongorestart
  ansible.builtin.systemd:
    name: mongod
    state: present
    enabled: yes

- name: nginxreload
  service:
    name: nginx
    state: restarted
